//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercuryEngApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MercuryEngApp.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Aborted.
        /// </summary>
        public static string Aborted {
            get {
                return ResourceManager.GetString("Aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update could not be Aborted.
        /// </summary>
        public static string AbortFailed {
            get {
                return ResourceManager.GetString("AbortFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Hardware Revision.
        /// </summary>
        public static string BoardHardwareRevision {
            get {
                return ResourceManager.GetString("BoardHardwareRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read board info successful..
        /// </summary>
        public static string BoardInfoReadSuccessful {
            get {
                return ResourceManager.GetString("BoardInfoReadSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write board info successful..
        /// </summary>
        public static string BoardInfoWriteSuccessful {
            get {
                return ResourceManager.GetString("BoardInfoWriteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Model Name.
        /// </summary>
        public static string BoardModelName {
            get {
                return ResourceManager.GetString("BoardModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Part Number.
        /// </summary>
        public static string BoardPartNumber {
            get {
                return ResourceManager.GetString("BoardPartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Part Number cannot be empty. Please select Board Part Number.
        /// </summary>
        public static string BoardPartNumberEmpty {
            get {
                return ResourceManager.GetString("BoardPartNumberEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Serial Number.
        /// </summary>
        public static string BoardSerialNumber {
            get {
                return ResourceManager.GetString("BoardSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes Received Erased: {0}.
        /// </summary>
        public static string BytesErased {
            get {
                return ResourceManager.GetString("BytesErased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes Received: {0}.
        /// </summary>
        public static string BytesReceived {
            get {
                return ResourceManager.GetString("BytesReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Frequency.
        /// </summary>
        public static string CenterFrequency {
            get {
                return ResourceManager.GetString("CenterFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Part Number.
        /// </summary>
        public static string ChannelPartNumber {
            get {
                return ResourceManager.GetString("ChannelPartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read channel number successful..
        /// </summary>
        public static string ChannelReadSuccessful {
            get {
                return ResourceManager.GetString("ChannelReadSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write channel number successful..
        /// </summary>
        public static string ChannelWriteSuccessful {
            get {
                return ResourceManager.GetString("ChannelWriteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checksum Failure.
        /// </summary>
        public static string CheckSumFailure {
            get {
                return ResourceManager.GetString("CheckSumFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select {0}.
        /// </summary>
        public static string ComboBoxNotSelected {
            get {
                return ResourceManager.GetString("ComboBoxNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparison Failure.
        /// </summary>
        public static string CompareFail {
            get {
                return ResourceManager.GetString("CompareFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirming.
        /// </summary>
        public static string Confirming {
            get {
                return ResourceManager.GetString("Confirming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth.
        /// </summary>
        public static string Depth {
            get {
                return ResourceManager.GetString("Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth value not accepted by TCD..
        /// </summary>
        public static string DepthNotAccepted {
            get {
                return ResourceManager.GetString("DepthNotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth sent successfully..
        /// </summary>
        public static string DepthSent {
            get {
                return ResourceManager.GetString("DepthSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diameter.
        /// </summary>
        public static string Diameter {
            get {
                return ResourceManager.GetString("Diameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envelope range set successfully..
        /// </summary>
        public static string EnvelopeRangeSet {
            get {
                return ResourceManager.GetString("EnvelopeRangeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envelope turned off..
        /// </summary>
        public static string EnvelopeTurnedOff {
            get {
                return ResourceManager.GetString("EnvelopeTurnedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envelope turned on..
        /// </summary>
        public static string EnvelopeTurnedOn {
            get {
                return ResourceManager.GetString("EnvelopeTurnedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase Failure.
        /// </summary>
        public static string EraseFail {
            get {
                return ResourceManager.GetString("EraseFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found..
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter value not accepted by TCD..
        /// </summary>
        public static string FilterNotAccepted {
            get {
                return ResourceManager.GetString("FilterNotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter sent successfully..
        /// </summary>
        public static string FilterSent {
            get {
                return ResourceManager.GetString("FilterSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format ID.
        /// </summary>
        public static string FormatID {
            get {
                return ResourceManager.GetString("FormatID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fractional BW.
        /// </summary>
        public static string Fractional {
            get {
                return ResourceManager.GetString("Fractional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Aborted the update..
        /// </summary>
        public static string HostAbort {
            get {
                return ResourceManager.GetString("HostAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impedance.
        /// </summary>
        public static string Impedance {
            get {
                return ResourceManager.GetString("Impedance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible Version.
        /// </summary>
        public static string IncompatVersion {
            get {
                return ResourceManager.GetString("IncompatVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertion Loss.
        /// </summary>
        public static string InsertionLoss {
            get {
                return ResourceManager.GetString("InsertionLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Invalid.
        /// </summary>
        public static string InvalidAddress {
            get {
                return ResourceManager.GetString("InvalidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Table Invalid.
        /// </summary>
        public static string InvalidTable {
            get {
                return ResourceManager.GetString("InvalidTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenght value not accepted by TCD..
        /// </summary>
        public static string LengthNotAccepted {
            get {
                return ResourceManager.GetString("LengthNotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length sent successfully..
        /// </summary>
        public static string LengthSent {
            get {
                return ResourceManager.GetString("LengthSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be more than {1} characters..
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microcontroller was disconnected..
        /// </summary>
        public static string MicrocontrollerDisconnected {
            get {
                return ResourceManager.GetString("MicrocontrollerDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a Float value..
        /// </summary>
        public static string MustBeFloat {
            get {
                return ResourceManager.GetString("MustBeFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Entry. {0} must be a number..
        /// </summary>
        public static string MustBeNumber {
            get {
                return ResourceManager.GetString("MustBeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read operating minutes successful..
        /// </summary>
        public static string OperatingMinutesReadSuccessful {
            get {
                return ResourceManager.GetString("OperatingMinutesReadSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packet Exported Successfully.
        /// </summary>
        public static string PacketExport {
            get {
                return ResourceManager.GetString("PacketExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhaseAngle.
        /// </summary>
        public static string PhaseAngle {
            get {
                return ResourceManager.GetString("PhaseAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical ID.
        /// </summary>
        public static string PhysicalID {
            get {
                return ResourceManager.GetString("PhysicalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        public static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power value not accepted by TCD..
        /// </summary>
        public static string PowerNotAccepted {
            get {
                return ResourceManager.GetString("PowerNotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power sent successfully..
        /// </summary>
        public static string PowerSent {
            get {
                return ResourceManager.GetString("PowerSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRF.
        /// </summary>
        public static string PRF {
            get {
                return ResourceManager.GetString("PRF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRF value not accepted by TCD..
        /// </summary>
        public static string PRFNotAccepted {
            get {
                return ResourceManager.GetString("PRFNotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRF sent successfully..
        /// </summary>
        public static string PRFSet {
            get {
                return ResourceManager.GetString("PRFSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An active probe was disconnected from TCD..
        /// </summary>
        public static string ProbeDisconnected {
            get {
                return ResourceManager.GetString("ProbeDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read probe info successful..
        /// </summary>
        public static string ProbeInfoReadSuccessful {
            get {
                return ResourceManager.GetString("ProbeInfoReadSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write probe info successful..
        /// </summary>
        public static string ProbeInfoWriteSuccessful {
            get {
                return ResourceManager.GetString("ProbeInfoWriteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe Model Name.
        /// </summary>
        public static string ProbeModelName {
            get {
                return ResourceManager.GetString("ProbeModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe Part Number.
        /// </summary>
        public static string ProbePartNumber {
            get {
                return ResourceManager.GetString("ProbePartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe Serial Number.
        /// </summary>
        public static string ProbeSerialNumber {
            get {
                return ResourceManager.GetString("ProbeSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value for {0} shoule be between {1} and {2}.
        /// </summary>
        public static string RangeValue {
            get {
                return ResourceManager.GetString("RangeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Failure.
        /// </summary>
        public static string ReadFail {
            get {
                return ResourceManager.GetString("ReadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending....
        /// </summary>
        public static string Sending {
            get {
                return ResourceManager.GetString("Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Depth.
        /// </summary>
        public static string StartDepth {
            get {
                return ResourceManager.GetString("StartDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update could not be started..
        /// </summary>
        public static string StartUpdateFailed {
            get {
                return ResourceManager.GetString("StartUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: {0}.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SVolume.
        /// </summary>
        public static string SVolume {
            get {
                return ResourceManager.GetString("SVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank Focal Length.
        /// </summary>
        public static string TankFocalLength {
            get {
                return ResourceManager.GetString("TankFocalLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCD is turned off..
        /// </summary>
        public static string TCDTurnedOff {
            get {
                return ResourceManager.GetString("TCDTurnedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCD is turned on..
        /// </summary>
        public static string TCDTurnedOn {
            get {
                return ResourceManager.GetString("TCDTurnedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be empty..
        /// </summary>
        public static string TextBoxBlank {
            get {
                return ResourceManager.GetString("TextBoxBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIC.
        /// </summary>
        public static string TIC {
            get {
                return ResourceManager.GetString("TIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout during update..
        /// </summary>
        public static string TimeOut {
            get {
                return ResourceManager.GetString("TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envelope limits turned off..
        /// </summary>
        public static string ToggleLimitsOff {
            get {
                return ResourceManager.GetString("ToggleLimitsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envelope limits turned on..
        /// </summary>
        public static string ToggleLimitsOn {
            get {
                return ResourceManager.GetString("ToggleLimitsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Receive Error.
        /// </summary>
        public static string UpdateError {
            get {
                return ResourceManager.GetString("UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verfying.
        /// </summary>
        public static string Verifying {
            get {
                return ResourceManager.GetString("Verifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Failure.
        /// </summary>
        public static string WriteFail {
            get {
                return ResourceManager.GetString("WriteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing.
        /// </summary>
        public static string Writing {
            get {
                return ResourceManager.GetString("Writing", resourceCulture);
            }
        }
    }
}
